name: foodgram workflow

on:
  push:
     branches:
       - master 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
  build_and_push_to_dockerhub: 
    name: Push docker image to docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aleksizverev/foodgram-project:latest
  deploy:
     runs-on: ubuntu-latest
     needs: build_and_push_to_dockerhub
     steps: 
       - uses: actions/checkout@master
       - name: copy files
         uses: appleboy/scp-action@master
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "ngnix/*, .env, docker-compose.yaml"
          target: "/home/aleksizverev/foodgram-project"
                   
       - name: creating and running container
         uses: appleboy/ssh-action@master
         with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
           cd ~ 
           sudo docker rmi foodgram-project -f
           sudo docker pull aleksizverev/foodgram-project:latest
           sudo docker-compose up --force-recreate -d web
       
 
  send_message:
     runs-on: ubuntu-latest
     needs: deploy
     steps:
     - name: send message
       uses: appleboy/telegram-action@master
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: $ Foodgram workflow успешно выполнен!
